# -*- coding: utf-8 -*-
"""SENAI-Python-Lista-Atividades-7-MATPLOTLIB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCb8XjJGXfxscVmZ_YvLh-qpjd7ReHvm
"""

import matplotlib.pyplot as plt
import numpy as np

"""## 1. Dados: Alturas (em centímetros) de uma amostra de estudantes de uma escola.

## np.random.seed(2)
## alturas = np.round(np.random.normal(170, 3, 300))

## Pergunta: Qual é a distribuição das alturas dos estudantes?

## Tarefa: Escolha entre histograma e gráfico de barras para representar os dados. Inclua título, rótulos dos eixos e legendas conforme apropriado.
"""

np.random.seed(2)
alturas = (np.random.normal(170, 3, 300))

plt.hist(alturas, bins=20, edgecolor='black')
plt.xlabel('Altura')
plt.ylabel('Idade')
plt.title('Distribuição de Alturas')
plt.show()

"""## 2. Dados: Notas em matemática e em ciências de uma turma ao longo do tempo.

## Tempo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
## Notas de Ciências: [80, 85, 70, 90, 75, 85, 95, 80, 85, 90]
## Notas de Matemática: [70, 75, 65, 85, 60, 80, 90, 75, 80, 85]

## Pergunta: Existe alguma relação entre as notas em matemática e em ciências ao longo do tempo?

## Tarefa: Escolha entre scatter plot e gráfico de linhas para representar os dados. Inclua título, rótulos dos eixos e legendas conforme apropriado.
"""

avaliacao = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
notasCiencias = [80, 85, 70, 90, 75, 85, 95, 80, 85, 90]
notasMatematica = [70, 75, 65, 85, 60, 80, 90, 75, 80, 85]

plt.plot(avaliacao, notasCiencias, notasMatematica)
plt.xlabel('Avaliacao')
plt.ylabel('Notas')
plt.title('Notas Matematica e Ciencia')
plt.xticks(rotation=45)
plt.grid()
plt.show()

"""## 3. Dados: Salários de uma empresa por departamento.

## DeptoA = [3000, 3200, 3500, 3800, 4000, 4200, 4500, 4800, 5000]
## DeptoB = [2800, 2900, 3100, 3300, 3500, 3600, 3800, 4000, 4200]
## DeptoC = [2500, 2700, 3000, 3200, 3300, 3500, 3700, 3900, 4100]

## Pergunta: Qual é a distribuição dos salários por departamento?

## Tarefa: Escolha entre box plot e histograma para representar os dados. Inclua título, rótulos dos eixos e legendas conforme apropriado.
"""

DeptoA = [3000, 3200, 3500, 3800, 4000, 4200, 4500, 4800, 5000]
DeptoB = [2800, 2900, 3100, 3300, 3500, 3600, 3800, 4000, 4200]
DeptoC = [2500, 2700, 3000, 3200, 3300, 3500, 3700, 3900, 4100]

plt.boxplot(DeptoA)
plt.title('Depto A')
plt.show()

plt.boxplot(DeptoB)
plt.title('Depto B')
plt.show()

plt.boxplot(DeptoC)
plt.title('Depto C')
plt.show()

"""## 4. Dados: Percentual de vendas de diferentes produtos em uma loja.

## produtos = ['Prod A', 'Prod B', 'Prod C', 'Prod D', 'Prod E']
## vendas_percentual = [30, 25, 20, 15, 10]

## Pergunta: Qual é a proporção de vendas de cada produto na loja?

##Tarefa: Escolha entre gráfico de pizza e gráfico de barras para representar os dados.
##Inclua título, rótulos dos eixos e legendas conforme apropriado.
"""

produtos = ['Prod A', 'Prod B', 'Prod C', 'Prod D', 'Prod E']
vendas_percentual = [30, 25, 20, 15, 10]

explode = [0.01] * len (vendas_percentual)
plt.pie (vendas_percentual, # dados das vendas
         labels = produtos, # rotulos externos
         autopct='%.1f%%', # textos nos pedacos
         explode=explode) # separa pedacos
plt.title('Distribuição de Vendas por Produto')
plt.show()

"""## Desafio. Modifique o exemplo apresentado anteriormente sobre gráfico de haste, onde utilizamos seno e cosseno, para produzir um mapa estilizado do estado de São Paulo, como ilustrado na figura abaixo."""

N = 31 # numero de pontos
x = np.arange(N)
y = np.sin(x / N * 1.6 * np.pi) # seno
z = np.cos(x / N * -1.6 * np.pi) # cosseno
y[y < 0] = 0
z[z > 0] = 0
plt.stem(x, y, linefmt='b')
plt.stem(x, z, linefmt='r')
plt.title('Mapa de São Paulo')
plt.show()