# -*- coding: utf-8 -*-
"""senai_python_aula7_MATPLOTLIB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjjMpv0KSn7z157EGig8lX7WyYp7rjJc
"""

import numpy as np
import matplotlib.pyplot as plt

# Matplotlib
N = 17
F= np.fft.fft(np.eye(N))
plt.plot(np.real (F), np.imag(F))
plt.axis('equal');
plt.show()

x = np.random.normal(50000, 15000, 1000)
y = np.random.normal(70000, 20000, 1000)

plt.hexbin(x, y, gridsize=20, cmap='Blues')
plt.xlabel('Salário')
plt.ylabel('Bônus')
plt.title('Distribuição de Salários e Bônus')
plt.colorbar(label='Contagem')
plt.show()